import "./globals.css";

export const metadata = {
  title: "Matrix Philippines - Software Solution for You",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased font-sans text-dark">{children}</body>
    </html>
  );
}
